name: Publish on Tag
on:
  release:
     types: [published]
jobs:
  call-publish:
    if: github.actor != 'perotoolsbot[bot]'
    uses: peroperogames/ToolsWorkflow/.github/workflows/publish-npm.yml@main
    secrets: inherit
